export enum Distrito {
  NORTE = 'NORTE',
  NORDESTE = 'NORDESTE',
  NOROESTE = 'NOROESTE',
  OESTE = 'OESTE',
  LESTE = 'LESTE',
  SUDESTE = 'SUDESTE',
  SUDOESTE = 'SUDOESTE',
  SUL = 'SUL',
  SERVICO_ESPECIALIZADO = 'SERVICO_ESPECIALIZADO'
}
